---
title: dongkwan-kim.github.io
timezone: Asia/Seoul
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
name: Dongkwan Kim's Blog
profile: https://avatars2.githubusercontent.com/u/14350049
author:
  facebook: dongkwan.kim.todoaskit
  github: dongkwan-kim
  twitter: _dongkwan_kim
copyright:
  year: 2017
  name: Dongkwan Kim
google-analytics:
  id: UA-79719474-1
disqus:
  id: dongkwans-blog
url: https://dongkwan-kim.github.io/
permalink: "/:title/"
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
nav:
- name: About
  url: "/about"
- name: Archive
  url: "/archive"
- name: Tags
  url: "/tags"
- name: Github
  url: https://github.com/dongkwan-kim
sass:
  sass_dir: _sass
  style: :compressed
gems:
- jekyll-seo-tag
- jekyll-paginate
- jekyll-admin
exclude:
- vendor
